from .hint import HintCommand
from .antihint import AntiHintCommand
from .thread import ThreadCommand
from .rr import RrCommand
from .help import HelpCommand
from .convert import ConvertCommand
from .weather import WeatherCommand
from .colour import ColourCommand
from .solver import SolverCommand
from .imagine import ImagineCommand
from .word_game import GuessingGameCommand
from .font import FontCommand
from .rv import RvCommand
from .translate import TranslateCommand
from .roles import UnderageCommand
from .highlight import HighlightCommand
from .eval import EvalCommand
from .purge import PurgeCommand
from .covid import CovidCommand
from .currency import CurrencyCommand
from .magiceye import MagiceyeCommand
from .exif import ExifCommand
from .roll import RollCommand
from .config import ConfigCommand
