from .antihint import AntiHintCommand
from .archive import ArchiveCommand
from .colour import ColourCommand
from .config import ConfigCommand
from .convert import ConvertCommand
from .covid import CovidCommand
from .currency import CurrencyCommand
from .eval import EvalCommand
from .exif import ExifCommand
from .font import FontCommand
from .help import HelpCommand
from .highlight import HighlightCommand
from .hint import HintCommand
from .imagine import ImagineCommand
from .magiceye import MagiceyeCommand
from .markov import MarkovAddChannelCommand, ImitateCommand
from .purge import PurgeCommand
from .remindme import RemindmeCommand
from .roles import UnderageCommand
from .roll import RollCommand
from .rr import RrCommand
from .rv import RvCommand
from .solver import SolverCommand
from .thread import ThreadCommand
from .translate import TranslateCommand
from .weather import WeatherCommand
from .word_game import GuessingGameCommand
from .whosaidit import WhoSaidItCommand
from .wordnik import WordnikCommand
from .profile import ProfileCommand
