from .archive import ArchiveCog
from .colour import ColourCog
from .config import ConfigCog
from .convert import ConvertCog
from .covid import CovidCog
from .eightball import EightballCog
from .roll import RollCog
from .rr import RrCog
from .rv import RvCog
from .translate import TranslateCog
from .weather import WeatherCog
from .word_game import WordgameCog
from .whosaidit import WhosaiditCog
from .wordnik import WordnikCog
from .enigmatics import EnigmaticsCog
from .eval import EvalCog
from .exif import ExifCog
from .font import FontCog
from .highlight import HighlightCog
from .imagine import ImagineCog
from .magiceye import MagiceyeCog
from .markov import MarkovCog
from .notpron import NotpronCog
from .purge import PurgeCog
from .remindme import RemindmeCog
from .rename import RenameCog
from .roles import RolesCog
from .openai import OpenAICog
from .guiser import GuiserCog
from .say import SayCog
from .softban import SoftbanCog
